./local ../experiment/graphs/RMAT.04.bin
./local ../experiment/graphs/RMAT.06.bin
./local ../experiment/graphs/RMAT.08.bin
./local ../experiment/graphs/RMAT.10.bin
./local ../experiment/graphs/RMAT.12.bin
./local ../experiment/graphs/RMAT.14.bin
./local ../experiment/graphs/RMAT.16.bin
./local ../experiment/graphs/RMAT.18.bin
./local ../experiment/graphs/RMAT.20.bin
./local ../experiment/graphs/RMAT.22.bin
./local ../experiment/graphs/SSCA2.04.bin
./local ../experiment/graphs/SSCA2.06.bin
./local ../experiment/graphs/SSCA2.08.bin
./local ../experiment/graphs/SSCA2.10.bin
./local ../experiment/graphs/SSCA2.12.bin
./local ../experiment/graphs/SSCA2.14.bin
./local ../experiment/graphs/SSCA2.16.bin
./local ../experiment/graphs/SSCA2.18.bin
./local ../experiment/graphs/SSCA2.20.bin
./local ../experiment/graphs/SSCA2.22.bin
./local ../experiment/graphs/UR.04.bin
./local ../experiment/graphs/UR.06.bin
./local ../experiment/graphs/UR.08.bin
./local ../experiment/graphs/UR.10.bin
./local ../experiment/graphs/UR.12.bin
./local ../experiment/graphs/UR.14.bin
./local ../experiment/graphs/UR.16.bin
./local ../experiment/graphs/UR.18.bin
./local ../experiment/graphs/UR.20.bin
./local ../experiment/graphs/UR.22.bin
